FROM node:20.19-alpine

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm ci

RUN npx prisma generate --schema=packages/db/prisma/schema.prisma

RUN npm run build

CMD ["npm","run","start-user-app"]